<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240318061821 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE quest ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE quest ALTER update_date TYPE DATE');
        $this->addSql('COMMENT ON COLUMN quest.update_date IS \'\'');
        $this->addSql('ALTER TABLE quest_completion_history ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE quest_completion_history ALTER complete_date TYPE DATE');
        $this->addSql('COMMENT ON COLUMN quest_completion_history.complete_date IS \'\'');
        $this->addSql('ALTER TABLE "user" ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE "user" ALTER update_date TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN "user".update_date IS \'\'');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE "user" ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE "user" ALTER update_date TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN "user".update_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE quest_completion_history ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE quest_completion_history ALTER complete_date TYPE DATE');
        $this->addSql('COMMENT ON COLUMN quest_completion_history.complete_date IS \'(DC2Type:date_immutable)\'');
        $this->addSql('ALTER TABLE quest ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE quest ALTER update_date TYPE DATE');
        $this->addSql('COMMENT ON COLUMN quest.update_date IS \'(DC2Type:date_immutable)\'');
    }
}
